// svelte/src/routes/home/HomeForum.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  import { resolve } from '$app/paths'
  import httpy from '$shared/utils/httpy'

  interface Row {
    id: number
    title: string
    replies_count: number
  }

  let rows: Row[] = []

  const load = async () => {
    const [data, err] = await httpy.get<Row[]>('/api/posts/recent')
    if (err) {
      console.error('recent posts', err)
      return
    }

    rows = data
  }

  onMount(load)
</script>

{#each rows as r (r.id)}
  <div class="p-1">
    <a href={resolve(`/forum/${r.id}`)}>
      {r.title}
      {#if r.replies_count > 0}
        <small>[{r.replies_count}]</small>
      {/if}
    </a>
  </div>
{/each}

// vue/src/views/home/HomeForum.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import httpy from '@common/utils/httpy'

interface Row {
  id: number
  title: string
  replies_count: number
}

const rows = ref<Row[]>([])

const load = async () => {
  const [data, err] = await httpy.get<Row[]>('/api/posts/recent')
  if (err) {
    console.error('recent posts', err)
    return
  }

  rows.value = data
}

onMounted(load)
</script>

<template>
  <div v-for="r in rows" :key="r.id" class="p-1">
    <a :href="`/forum/${r.id}`">
      {{ r.title }}
      <small v-if="r.replies_count > 0">[{{ r.replies_count }}]</small>
    </a>
  </div>
</template>
