// mwz/skins/ZetaSkin/vue/src/components/toc/TocNode.vue
<!-- TocNode.vue -->
<script setup lang="ts">
import type { PropType } from 'vue'
import { computed } from 'vue'

import type { Section } from '@/types/toc'

defineOptions({ name: 'TocNode' })

const props = defineProps({
  section: { type: Object as PropType<Section>, required: true },
  targetIds: { type: Array as PropType<string[]>, required: true },
  depth: { type: Number, default: 0 },
  showRail: { type: Boolean, default: true },
  onNavigate: {
    type: Function as PropType<(id: string) => void>,
    required: true,
  },
})

const anchor = computed(() => props.section.anchor ?? '')
const children = computed(() => props.section['array-sections'] ?? [])
const label = computed(() =>
  props.section.line.replace(/<\/?[^>]+>/ig, ' ').trim()
)
const number = computed(() => props.section.number)

const isInView = computed(
  () => !!anchor.value && props.targetIds.includes(anchor.value)
)

const onClick = (e: MouseEvent) => {
  e.preventDefault()
  if (!anchor.value) return
  props.onNavigate(anchor.value)
}
</script>

<template>
  <a :href="`#${anchor}`" :class="{ 'border-[#888]': isInView && props.showRail, 'border-l-2': props.showRail }"
    class="flex w-full items-start gap-1 z-text2 hover:no-underline hover:text-(--link)"
    :style="{ paddingLeft: `calc((${props.depth} + 1) * 0.75rem)` }" @click="onClick">
    <span class="shrink-0 z-text4">
      <span>{{ number }}</span>
      <span v-if="depth === 0">.</span>
    </span>
    <span class="flex-1">{{ label }}</span>
  </a>

  <ul v-if="children?.length > 0" class="p-0 list-none" role="list">
    <li v-for="s in children" :key="s.index ?? s.anchor" class="m-0">
      <TocNode :section="s" :target-ids="targetIds" :depth="props.depth + 1" :show-rail="props.showRail"
        :on-navigate="props.onNavigate" />
    </li>
  </ul>
</template>

// mwz/skins/ZetaSkin/svelte/src/components/toc/TocNode.svelte
<script lang="ts">
  import type { Section } from '$lib/types/toc'

  import TocNode from './TocNode.svelte'

  export let section: Section
  export let targetIds: string[] = []
  export let depth = 0
  export let showRail = true
  export let onNavigate: (id: string) => void

  $: anchor = section?.anchor ?? ''
  $: children = section?.['array-sections'] ?? []
  $: label = (section?.line ?? '').replace(/<\/?[^>]+>/gi, ' ').trim()
  $: number = section?.number ?? ''
  $: isInView = !!anchor && targetIds.includes(anchor)

  const onClick = (e: MouseEvent) => {
    e.preventDefault()
    if (!anchor) return
    if (onNavigate) onNavigate(anchor)
  }
</script>

<a
  href={`#${anchor}`}
  class={`flex w-full items-start gap-1 z-text2 hover:no-underline hover:text-(--link) ${showRail ? 'border-l-2' : ''} ${isInView && showRail ? 'border-[#888]' : ''}`}
  style={`padding-left: calc((${depth} + 1) * 0.75rem);`}
  on:click={onClick}
>
  <span class="shrink-0 z-text4">
    <span>{number}</span>
    {#if depth === 0}
      <span>.</span>
    {/if}
  </span>
  <span class="flex-1">{label}</span>
</a>

{#if children?.length > 0}
  <ul class="p-0 list-none" role="list">
    {#each children as s (s.index ?? s.anchor)}
      <li class="m-0">
        <TocNode section={s} {targetIds} depth={depth + 1} {showRail} {onNavigate} />
      </li>
    {/each}
  </ul>
{/if}
