// mwz/skins/ZetaSkin/svelte/src/components/binder/BinderNode.svelte
<script context="module" lang="ts">
  export interface BinderNodeData {
    id: number
    text: string
    href?: string
    new?: boolean
    nodes?: BinderNodeData[]
  }
</script>

<script lang="ts">
  import { mdiChevronRight } from '@mdi/js'
  import { createEventDispatcher, onMount, tick } from 'svelte'

  import ZIcon from '$shared/ui/ZIcon.svelte'

  import BinderNode from './BinderNode.svelte'

  export let node: BinderNodeData
  export let depth = 0
  export let wgArticleId: number
  export let binderId: number

  const dispatch = createEventDispatcher<{ reveal: void }>()

  let expanded = depth === 0
  let rowEl: HTMLElement | null = null

  const key = () => String(node?.id ?? '')
  const storageKey = () => `binder-${binderId}`

  const readMap = () => {
    try {
      const raw = localStorage.getItem(storageKey())
      if (!raw) return {}
      const parsed = JSON.parse(raw)
      return parsed && typeof parsed === 'object' ? (parsed as Record<string, number>) : {}
    } catch {
      return {}
    }
  }

  const writeMap = (map: Record<string, number>) => {
    try {
      localStorage.setItem(storageKey(), JSON.stringify(map))
    } catch {
      // ignore storage failures
    }
  }

  const persist = () => {
    const map = readMap()
    map[key()] = expanded ? 1 : 0
    writeMap(map)
  }

  const toggle = () => {
    expanded = !expanded
    persist()
  }

  const handleReveal = () => {
    if (!expanded) {
      expanded = true
      persist()
    }
    dispatch('reveal')
  }

  const isCurrent = () => node?.id === wgArticleId
  const isLink = () => !!node?.href
  const hasChildren = () => !!node?.nodes?.length

  onMount(async () => {
    const map = readMap()
    const saved = map[key()]
    if (saved === 0 || saved === 1) expanded = !!saved

    if (isCurrent()) {
      dispatch('reveal')
      await tick()
      rowEl?.scrollIntoView({ block: 'center' })
    }
  })
</script>

<li class="flex flex-col">
  <div class="row flex items-stretch hover:bg-gray-500/15" bind:this={rowEl}>
    <svelte:element
      this={isLink() ? 'a' : 'div'}
      href={node?.href || undefined}
      class={`flex flex-1 px-2 hover:no-underline ${isCurrent() ? 'font-bold' : ''} ${node?.new ? 'new' : ''}`}
      title={node?.text}
    >
      <span style={`padding-left: ${depth}rem`}>{node?.text}</span>
    </svelte:element>

    {#if hasChildren()}
      <button class="w-6 h-6 grid place-items-center rounded-full hover:bg-gray-500/30" on:click|stopPropagation|preventDefault={toggle}>
        <ZIcon path={mdiChevronRight} class={`transition-transform ${expanded ? 'rotate-90' : ''}`} />
      </button>
    {/if}
  </div>

  {#if hasChildren()}
    <ul class="p-0 m-0" style={`display: ${expanded ? 'block' : 'none'}`}>
      {#each node.nodes as n (n.text)}
        <BinderNode node={n} depth={depth + 1} {wgArticleId} {binderId} on:reveal={handleReveal} />
      {/each}
    </ul>
  {/if}
</li>

// mwz/skins/ZetaSkin/vue/src/components/binder/BinderNode.vue
<!-- BinderNode.vue -->
<script setup lang="ts">
import ZIcon from '@common/ui/ZIcon.vue'
import { mdiChevronRight } from '@mdi/js'
import { useStorage } from '@vueuse/core'
import { computed, nextTick, onMounted, type PropType, ref, watchEffect } from 'vue'

import type { BinderNodeData } from '@/types/binder'

defineOptions({
  name: 'BinderNode'
})

const props = defineProps({
  node: { type: Object as PropType<BinderNodeData>, required: true },
  depth: { type: Number, default: 0 },
  wgArticleId: { type: Number, required: true },
  binderId: { type: Number, required: true },
})
const emit = defineEmits<{ (e: 'reveal'): void }>()

const isCurrent = computed(() => props.node.id === props.wgArticleId)
const isLink = computed(() => !!props.node.href)
const hasChildren = computed(() => !!props.node.nodes?.length)

const key = String(props.node.id)
const storageKey = computed(() => `binder-${props.binderId}`)
const expandedMap = useStorage<Record<string, number>>(storageKey, {}, localStorage)
const expanded = ref(props.depth === 0)
const rowRef = ref<HTMLElement | null>(null)

watchEffect(() => {
  const saved = expandedMap.value[key]
  if (saved === 0 || saved === 1) expanded.value = !!saved
})

function persist() {
  expandedMap.value[key] = expanded.value ? 1 : 0
}

function toggle() {
  expanded.value = !expanded.value
  persist()
}

function handleReveal() {
  if (!expanded.value) {
    expanded.value = true
    persist()
  }
  emit('reveal')
}

async function centerScrollIfCurrent() {
  if (!isCurrent.value) return
  emit('reveal')
  await nextTick()
  rowRef.value?.scrollIntoView({ block: 'center' })
}

onMounted(centerScrollIfCurrent)
</script>

<template>
  <li class="flex flex-col">
    <div class="row flex items-stretch hover:bg-gray-500/15" ref="rowRef">
      <component :is="isLink ? 'a' : 'div'" :href="node.href || undefined" class="flex flex-1 px-2 hover:no-underline"
        :class="{ 'font-bold': isCurrent, 'new': node.new }" :title="node.text">
        <span :style="{ paddingLeft: `${depth}rem` }">{{ node.text }}</span>
      </component>

      <button v-if="hasChildren" class="w-6 h-6 grid place-items-center rounded-full hover:bg-gray-500/30"
        @click.stop.prevent="toggle">
        <ZIcon :path="mdiChevronRight" class="transition-transform" :class="{ 'rotate-90': expanded }" />
      </button>
    </div>

    <ul v-if="hasChildren" v-show="expanded" class="p-0 m-0">
      <BinderNode v-for="n in node.nodes" :key="n.text" :node="n" :depth="depth + 1" :wgArticleId="wgArticleId"
        :binderId="binderId" @reveal="handleReveal" />
    </ul>
  </li>
</template>
