// vue/common/components/CAds.vue
<script setup lang="ts">
import { nextTick, onMounted, watch } from 'vue'

declare global {
  interface Window {
    adsbygoogle?: unknown[]
  }
}

const props = defineProps<{
  client: string
  slot: string
  style?: string
}>()

function pushAd() {
  try {
    const w = window as Window
    w.adsbygoogle = w.adsbygoogle || []
    w.adsbygoogle.push({})
  } catch {
    // ignore
  }
}

async function render() {
  await nextTick()
  pushAd()
}

onMounted(() => {
  render()
})

watch(
  () => props.slot,
  () => {
    render()
  }
)
</script>

<template>
  <ins class="adsbygoogle" :style="style || 'display:inline-block'" :data-ad-client="client" :data-ad-slot="slot" />
</template>

// svelte/src/shared/components/CAds.svelte
<svelte:options customElement={{ tag: 'c-ads', shadow: 'none' }} />

<script lang="ts">
  import { onMount, tick } from 'svelte'

  export let client: string
  export let slot: string
  export let style: string | undefined

  const pushAd = () => {
    try {
      window.adsbygoogle = window.adsbygoogle || []
      window.adsbygoogle.push({})
    } catch {
      // ignore
    }
  }

  const render = async () => {
    await tick()
    pushAd()
  }

  onMount(() => {
    void render()
  })

  $: if (slot) {
    void render()
  }

  const defaultStyle = 'display:block;width:100%;height:100%;'
  $: insStyle = style ? `${defaultStyle}${style}` : defaultStyle
</script>

<ins class="adsbygoogle" style={insStyle} data-ad-client={client} data-ad-slot={slot}></ins>
