// svelte/src/shared/ui/ZTextarea.svelte
<script lang="ts">
  import { afterUpdate, onMount } from 'svelte'
  import { createEventDispatcher } from 'svelte'

  export let modelValue = ''
  export let placeholder: string | undefined
  export let id: string
  export let maxHeight: number | undefined

  const dispatch = createEventDispatcher<{ 'update:modelValue': string }>()

  let textareaEl: HTMLTextAreaElement | null = null

  function adjustHeight() {
    if (!textareaEl) return
    const max = maxHeight ?? 200

    textareaEl.style.height = 'auto'
    const scrollHeight = textareaEl.scrollHeight
    const newHeight = Math.min(scrollHeight, max)

    textareaEl.style.height = `${newHeight}px`
    textareaEl.style.overflowY = scrollHeight > max ? 'auto' : 'hidden'
  }

  function handleInput(event: Event) {
    const target = event.target as HTMLTextAreaElement
    dispatch('update:modelValue', target.value)
    queueMicrotask(adjustHeight)
  }

  onMount(adjustHeight)
  afterUpdate(adjustHeight)
</script>

<textarea
  bind:this={textareaEl}
  class="w-full resize-none overflow-y-hidden bg-inherit p-2 outline-none"
  {id}
  value={modelValue}
  {placeholder}
  on:input={handleInput}
></textarea>

// vue/common/ui/ZTextarea.vue
<script setup lang="ts">
import { nextTick, ref, watch } from 'vue'

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
}>()

const props = defineProps<{
  modelValue: string
  placeholder?: string
  id: string
  maxHeight?: number
}>()

const textareaEl = ref<HTMLTextAreaElement | null>(null)

function adjustHeight() {
  const el = textareaEl.value
  if (!el) return

  const max = props.maxHeight ?? 200

  el.style.height = 'auto'
  const scrollHeight = el.scrollHeight
  const newHeight = Math.min(scrollHeight, max)

  el.style.height = `${newHeight}px`
  el.style.overflowY = scrollHeight > max ? 'auto' : 'hidden'
}

function handleInput(event: Event) {
  const target = event.target as HTMLTextAreaElement
  emit('update:modelValue', target.value)
  nextTick(adjustHeight)
}

watch(() => props.modelValue, () => { nextTick(adjustHeight) }, { immediate: true })
</script>

<template>
  <textarea ref="textareaEl" class="w-full p-2 bg-inherit resize-none outline-none overflow-y-hidden" :id="id"
    :value="modelValue" :placeholder="placeholder" @input="handleInput" />
</template>
