// svelte/src/shared/ui/toast/ToastHost.svelte
<svelte:options customElement={{ tag: 'toast-host', shadow: 'none' }} />

<script lang="ts">
  import { fly } from 'svelte/transition'

  import { toasts } from './toast'
</script>

<div class="fixed right-2 top-2 z-50">
  {#each $toasts as toast (toast.id)}
    <div class="mt-1 w-56 rounded bg-slate-500/80 text-white shadow-md" in:fly={{ y: 6, duration: 200 }} out:fly={{ y: 6, duration: 200 }}>
      <div class="px-4 py-2">{toast.message}</div>
      <hr class="toast-bar h-1 rounded bg-black/50" style={`animation-duration: ${toast.timeout}ms`} />
    </div>
  {/each}
</div>

<style>
  @keyframes toast-bar {
    from {
      width: 100%;
    }

    to {
      width: 0%;
    }
  }

  .toast-bar {
    animation: toast-bar linear forwards;
  }
</style>

// vue/common/ui/toast/ToastHost.vue
<!-- ToastHost.vue -->
<template>
  <Teleport to="body">
    <div class="fixed top-2 right-2 z-50">
      <TransitionGroup name="fade" tag="div">
        <div v-for="t in toasts" :key="t.id" class="w-56 mt-1 rounded bg-slate-500/80 text-white shadow-md">
          <div class="px-4 py-2">{{ t.message }}</div>
          <hr class="toast-bar h-1 bg-black/50 rounded" :style="{ animationDuration: `${t.timeout}ms` }" />
        </div>
      </TransitionGroup>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { toasts } from './toast'
</script>

<style scoped>
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(6px);
}

.fade-enter-active,
.fade-leave-active {
  transition: all 0.3s ease;
}

@keyframes toast-bar {
  from {
    width: 100%;
  }

  to {
    width: 0%;
  }
}

.toast-bar {
  animation: toast-bar linear forwards;
}
</style>
