// svelte/src/routes/forum/editor/MenuItem.svelte
<script lang="ts">
  import ZIcon from '$shared/ui/ZIcon.svelte'

  import type { ItemData } from './types'

  export let itemData: ItemData
</script>

<button
  type="button"
  class={`menu-item ${itemData.isActive && itemData.isActive() ? 'is-active' : ''}`}
  title={itemData.title ?? ''}
  on:click={() => itemData.action?.()}
>
  <ZIcon path={itemData.icon ?? ''} />
</button>

<style>
  @reference 'tailwindcss';

  .menu-item {
    @apply ml-1 rounded cursor-pointer;
  }

  .menu-item :global(svg) {
    @apply h-7 w-7 p-1 fill-current;
  }

  .menu-item.is-active,
  .menu-item:hover {
    @apply bg-zinc-200 dark:bg-zinc-800;
  }
</style>

// vue/src/views/forum/editor/MenuItem.vue
<!-- MenuItem.vue -->
<script setup lang="ts">
import ZIcon from '@common/ui/ZIcon.vue'
import type { PropType } from 'vue'

import type { ItemData } from './types'

defineProps({
  itemData: { type: Object as PropType<ItemData>, required: true },
})
</script>

<template>
  <button type="button" class="menu-item" :class="{ 'is-active': itemData.isActive ? itemData.isActive() : null }"
    :title="itemData.title ?? ''" @click="itemData.action">
    <ZIcon :path="itemData.icon ?? ''" />
  </button>
</template>
