// svelte/src/routes/tool/write-request/WriteRequest.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { mdiDelete } from '@mdi/js'
  import { get } from 'svelte/store'

  import { page } from '$app/state'
  import ThePagination from '$lib/components/pagination/ThePagination.svelte'
  import type { PaginateData } from '$lib/components/pagination/types'
  import useAuthStore from '$lib/stores/auth'
  import AvatarUser from '$shared/components/avatar/AvatarUser.svelte'
  import { showConfirm } from '$shared/ui/confirm/confirm'
  import { showToast } from '$shared/ui/toast/toast'
  import ZButton from '$shared/ui/ZButton.svelte'
  import ZIcon from '$shared/ui/ZIcon.svelte'
  import ZSpinner from '$shared/ui/ZSpinner.svelte'
  import httpy from '$shared/utils/httpy'

  import WriteRequestNew from './WriteRequestNew.svelte'

  interface Row {
    hit: number
    id: number
    user_id: number
    user_name: string
    writer_id: number
    writer_name?: string
    rate: number
    ref: number
    title: string
    writed_at: string
    updated_at: string
  }

  interface RespData {
    current_page: number
    data: Row[]
    last_page: number
  }

  interface Count {
    done: number
    todo: number
  }

  type Mode = 'todo' | 'todo-top' | 'done'

  const auth = useAuthStore()
  const canWrite = auth.canWrite
  const canDelete = auth.canDelete

  let mode = $state<Mode>('todo')
  let respData = $state<RespData>({ current_page: 1, data: [], last_page: 1 })
  let paginateData = $state<PaginateData | null>(null)
  let currentPage = $state(1)
  let showModal = $state(false)
  let count = $state<Count>({ done: 0, todo: 0 })
  let loading = $state(true)

  let observedRoutePage = 0

  let routePage = $derived.by(() => {
    const p = Number(page.url.searchParams.get('page'))
    return Number.isFinite(p) && p > 0 ? p : 1
  })

  $effect(() => {
    if (routePage !== observedRoutePage) {
      observedRoutePage = routePage
      currentPage = routePage
      void fetchData()
    }
  })

  async function fetchCount() {
    const [data, err] = await httpy.get<Count>('/api/write-request/count')
    if (err) {
      console.error(err)
      return
    }
    count = data
  }

  async function fetchPage() {
    const [data, err] = await httpy.get<RespData>(`/api/write-request/${mode}`, {
      page: String(currentPage),
    })

    if (err) {
      console.error(err)
      loading = false
      return
    }

    respData = data
    paginateData = {
      current_page: data.current_page,
      last_page: data.last_page,
      path: '/tool/write-request',
    }

    loading = false
  }

  async function fetchData() {
    loading = true
    await fetchCount()
    if (typeof window !== 'undefined') {
      window.scrollTo(0, 0)
    }
    await fetchPage()
  }

  async function openModal() {
    if (!get(canWrite)) {
      window.location.href = '/login?redirect=/tool/write-request'
      return
    }
    showModal = true
  }

  function closeModal() {
    showModal = false
    void fetchData()
  }

  function setMode(nextMode: Mode) {
    mode = nextMode
    void fetchData()
  }

  async function del(row: Row) {
    const ok = await showConfirm(`'${row.title}' 작성요청을 삭제하시겠습니까 ? `)
    if (!ok) return

    const [, err] = await httpy.delete(`/api/write-request/${row.id}`)
    if (err) {
      console.error(err)
      return
    }

    await fetchData()
    showToast('삭제 완료')
  }

  async function recommend(row: Row) {
    if (!get(canWrite)) {
      window.location.href = '/login?redirect=/tool/write-request'
      return
    }

    const [data, err] = await httpy.post<{ ok: boolean; rate: number }>(`/api/write-request/${row.id}/recommend`)
    if (err) {
      console.error(err)
      return
    }

    row.rate = data.rate
  }

  function getTitleHref(row: Row) {
    if (mode === 'done') return `/wiki/${row.title}`
    return `/w/index.php?search=${row.title}`
  }

  function getDateText(row: Row) {
    return row.updated_at.substring(0, 10)
  }

  function getWrittenDateText(row: Row) {
    const writedAt = (row.writed_at || '').trim()
    if (writedAt) return writedAt.substring(0, 10)
    return row.updated_at.substring(0, 10)
  }

  function getRequestUser(row: Row) {
    return { id: row.user_id, name: row.user_name }
  }

  function getDisplayUser(row: Row) {
    return {
      id: row.writer_id > 0 ? row.writer_id : row.user_id,
      name: row.writer_name || row.user_name,
    }
  }
</script>

<div class="p-5">
  <h2 class="my-5 text-2xl font-bold">작성 요청</h2>
  <WriteRequestNew show={showModal} on:close={closeModal} />

  <div class="pb-3">
    <button
      type="button"
      class={`inline-block rounded-l border p-3 ${mode === 'todo' ? 'bg-slate-100 dark:bg-slate-700' : 'bg-white dark:bg-slate-900'}`}
      onclick={() => setMode('todo')}
    >
      요청 <span class="rounded-full bg-gray-400 px-1 text-xs text-white">{count.todo}</span>
    </button>
    <button
      type="button"
      class={`inline-block border border-l-0 p-3 ${mode === 'todo-top' ? 'bg-slate-100 dark:bg-slate-700' : 'bg-white dark:bg-slate-900'}`}
      onclick={() => setMode('todo-top')}
    >
      추천
    </button>
    <button
      type="button"
      class={`inline-block rounded-r border border-l-0 p-3 ${mode === 'done' ? 'bg-slate-100 dark:bg-slate-700' : 'bg-white dark:bg-slate-900'}`}
      onclick={() => setMode('done')}
    >
      완료 <span class="rounded-full bg-gray-400 px-2 text-xs text-white">{count.done}</span>
    </button>
  </div>

  <table class="mytable z-card w-full">
    <thead class="z-base3">
      <tr>
        <th>번호</th>
        <th>제목</th>
        <th>추천</th>
        <th>검색</th>
        <th>역링크</th>
        {#if mode === 'done'}
          <th>요청</th>
          <th>작성</th>
        {:else}
          <th>요청일</th>
          <th>요청자</th>
        {/if}
      </tr>
    </thead>

    {#if loading}
      <thead>
        <tr>
          <th colspan={7} class="p-0!">
            <div class="progress-wrap">
              <div class="progress-bar"></div>
            </div>
            {#if !respData.data.length}
              <div class="flex h-32 items-center justify-center">
                <ZSpinner />
              </div>
            {/if}
          </th>
        </tr>
      </thead>
    {/if}

    <tbody>
      {#each respData.data as row (row.id)}
        <tr class="align-top border-b border-[#88888866]">
          <td class="px-2 text-center">{row.id}</td>
          <td class="w-[35%]">
            <a href={getTitleHref(row)} rel="external" class={mode === 'done' ? '' : 'new'}>{row.title}</a>
            {#if $canDelete(row.user_id)}
              <ZButton color="ghost" class="py-1 align-middle leading-none text-[#888]" on:click={() => del(row)}>
                <ZIcon path={mdiDelete} />
              </ZButton>
            {/if}
          </td>
          <td class="text-center">
            {#if mode === 'done'}
              {row.rate}
            {:else}
              <ZButton class="min-w-10 px-2 py-1" onclick={() => recommend(row)}>{row.rate}</ZButton>
            {/if}
          </td>
          <td class="text-center">{row.hit}</td>
          <td class="text-center">
            <a href={`/wiki/특수:가리키는문서/${row.title}`} rel="external" class="btn">{row.ref}</a>
          </td>
          {#if mode === 'done'}
            <td class="text-center">
              <div>{getDateText(row)}</div>
              <div class="mt-1">
                <AvatarUser user={getRequestUser(row)} />
              </div>
            </td>
            <td class="text-center">
              <div>{getWrittenDateText(row)}</div>
              <div class="mt-1">
                <AvatarUser user={getDisplayUser(row)} />
              </div>
            </td>
          {:else}
            <td class="text-center">{getDateText(row)}</td>
            <td class="user">
              <AvatarUser user={getRequestUser(row)} />
            </td>
          {/if}
        </tr>
      {/each}
    </tbody>
  </table>

  <div class="py-4 text-right">
    <ZButton disabled={!$canWrite} onclick={openModal}>등록</ZButton>
  </div>

  {#if paginateData}
    <div class="pb-4">
      <ThePagination {paginateData} />
    </div>
  {/if}
</div>

<style>
  th,
  td {
    padding: 0.5rem 1rem;
  }

  .progress-wrap {
    overflow: hidden;
    width: 100%;
    height: 4px;
    background: rgba(5, 114, 206, 0.05);
  }

  .progress-bar {
    width: 100%;
    height: 100%;
    animation: write-request-progress 1s infinite linear;
    background: rgb(5, 114, 206);
    transform-origin: 0% 50%;
  }

  @keyframes write-request-progress {
    0% {
      transform: translateX(0) scaleX(0);
    }

    40% {
      transform: translateX(0) scaleX(0.4);
    }

    100% {
      transform: translateX(100%) scaleX(0.5);
    }
  }
</style>

// vue/src/views/tool/writeRequest/WriteRequest.vue
<!-- @/views/tool/writeRequest/WriteRequest.vue -->
<script setup lang="ts">
import AvatarUser from '@common/components/avatar/AvatarUser.vue'
import CProgressBar from '@common/components/CProgressBar.vue'
import { useConfirm } from '@common/composables/confirm/useConfirm'
import { useToast } from '@common/composables/toast/useToast'
import ZButton from '@common/ui/ZButton.vue'
import ZIcon from '@common/ui/ZIcon.vue'
import ZSpinner from '@common/ui/ZSpinner.vue'
import httpy from '@common/utils/httpy'
import { mdiDelete } from '@mdi/js'
import { ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'

import ThePagination from '@/components/pagination/ThePagination.vue'
import type { PaginateData } from '@/components/pagination/types'
import useAuthStore from '@/stores/auth'

import WriteRequestNew from './WriteRequestNew.vue'

interface Row {
  hit: number
  id: number
  user_id: number
  user_name: string
  rate: number
  ref: number
  title: string
  writed_at: string
  updated_at: string
}

interface RespData {
  current_page: number
  data: Row[]
  last_page: number
}

interface Count {
  done: number
  todo: number
}

const me = useAuthStore()
const route = useRoute()
const router = useRouter()
const toast = useToast()
const confirm = useConfirm()

const mode = ref<'todo' | 'todo-top' | 'done'>('todo')
const respData = ref({} as RespData)
const paginateData = ref<PaginateData | null>(null)
const page = ref(1)
const showModal = ref(false)
const count = ref({} as Count)
const loading = ref(true)

const retries = 0

function resolvePageFromRoute(): number {
  const queryPage = Number(String(route.query.page ?? ''))
  if (Number.isFinite(queryPage) && queryPage > 0) return queryPage

  const paramPage = Number(String(route.params.page ?? ''))
  if (Number.isFinite(paramPage) && paramPage > 0) return paramPage

  return 1
}

async function fetchCount() {
  const [data, err] = await httpy.get<Count>('/api/write-request/count')
  if (err) {
    console.error(err)
    return
  }
  count.value = data
}

async function fetchPage() {
  const [data, err] = await httpy.get<RespData>(`/api/write-request/${mode.value}`, {
    page: String(page.value),
  })

  if (err) {
    console.error(err)
    loading.value = false
    return
  }

  respData.value = data
  paginateData.value = {
    current_page: data.current_page,
    last_page: data.last_page,
    path: '/tool/write-request',
  }

  loading.value = false
}

function fetchData() {
  loading.value = true

  fetchCount()

  page.value = resolvePageFromRoute()
  if (retries < 1) window.scrollTo(0, 0)

  fetchPage()
}

function openModal() {
  if (!me.canWrite()) {
    router.push({ path: '/login', query: { redirect: '/tool/write-request' } })
    return
  }
  showModal.value = true
}

function closeModal() {
  showModal.value = false
  fetchData()
}

function setMode(m: 'todo' | 'todo-top' | 'done') {
  mode.value = m
  fetchData()
}

async function del(row: Row) {
  const ok = await confirm(`'${row.title}' 작성요청을 삭제하시겠습니까 ? `)
  if (!ok) return

  const [, err] = await httpy.delete(`/api/write-request/${row.id}`)
  if (err) {
    console.error(err)
    return
  }

  fetchData()
  toast.show('삭제 완료')
}

watch(() => [route.params.page, route.query.page], fetchData, { immediate: true })
</script>

<template>
  <div class="p-5">
    <h2 class="my-5 text-2xl font-bold">
      작성 요청
    </h2>
    <WriteRequestNew :show="showModal" @close="closeModal" />

    <div v-if="count" class="pb-3">
      <button type="button" class="inline-block p-3 border rounded-l"
        :class="[mode == 'todo' ? 'bg-slate-100 dark:bg-slate-700' : 'bg-white dark:bg-slate-900']"
        @click="setMode('todo')">
        요청 <span class="text-xs rounded-full px-1 bg-gray-400 text-white">{{ count.todo }}</span>
      </button>
      <button type="button" class="inline-block p-3 border border-l-0"
        :class="[mode == 'todo-top' ? 'bg-slate-100 dark:bg-slate-700' : 'bg-white dark:bg-slate-900']"
        @click="setMode('todo-top')">
        추천
      </button>
      <button type="button" class="inline-block p-3 border border-l-0 rounded-r"
        :class="[mode == 'done' ? 'bg-slate-100 dark:bg-slate-700' : 'bg-white dark:bg-slate-900']"
        @click="setMode('done')">
        완료 <span class="text-xs rounded-full px-2 bg-gray-400 text-white">{{ count.done }}</span>
      </button>
    </div>

    <table class="mytable w-full z-card">
      <thead class="z-table-header">
        <tr>
          <th>번호</th>
          <th>제목</th>
          <th>추천</th>
          <th>검색</th>
          <th>역링크</th>
          <th>요청일</th>
          <th>요청자</th>
        </tr>
      </thead>

      <thead v-if="loading">
        <tr>
          <th colspan="9" class="!p-0">
            <CProgressBar />
            <div v-if="!respData.data" class="h-32 flex items-center justify-center">
              <ZSpinner />
            </div>
          </th>
        </tr>
      </thead>

      <tbody>
        <tr v-for="(row, rowKey) in respData.data" :key="rowKey" class="align-top border-b border-[#88888866]">
          <td class="text-center px-2">
            {{ row.id }}
          </td>
          <td class="w-[35%]">
            <a v-if="mode == 'todo'" :href="`/w/index.php?search=${row.title}`" class="new">{{ row.title }}</a>
            <a v-else-if="mode == 'todo-top'" :href="`/w/index.php?search=${row.title}`" class="new">{{ row.title }}</a>
            <a v-else :href="`/wiki/${row.title}`">{{ row.title }}</a>
            <ZButton v-if="me.canDelete(row.user_id)" color="ghost" class="text-[#888] py-1 align-middle leading-none"
              @click="del(row)">
              <ZIcon :path="mdiDelete" />
            </ZButton>
          </td>
          <td class="text-center">
            {{ row.rate }}
          </td>
          <td class="text-center">
            {{ row.hit }}
          </td>
          <td class="text-center">
            <a :href="`/wiki/특수:가리키는문서/${row.title}`" class="btn">
              {{ row.ref }}
            </a>
          </td>
          <td class="text-center">
            {{ row.updated_at.substring(0, 10) }}
          </td>
          <td class="user">
            <AvatarUser :user="{ id: row.user_id, name: row.user_name }" />
          </td>
        </tr>
      </tbody>
    </table>

    <div class="py-4 text-right">
      <ZButton :disabled="!me.canWrite()" @click="openModal">등록</ZButton>
    </div>

    <ThePagination v-if="paginateData" class="pb-4" :paginate-data="paginateData" />
  </div>
</template>

<style scoped>
th,
td {
  padding: .5rem 1rem;
}
</style>
