// svelte/src/routes/tool/write-request/WriteRequestNew.svelte
<script lang="ts">
  import { tick } from 'svelte'
  import { createEventDispatcher } from 'svelte'

  import titleExist from '$lib/utils/mediawiki'
  import { showToast } from '$shared/ui/toast/toast'
  import ZModal from '$shared/ui/ZModal.svelte'
  import httpy from '$shared/utils/httpy'

  type State = 'idle' | 'checking' | 'available' | 'exists'

  export let show = false

  const dispatch = createEventDispatcher<{ close: void }>()

  let title = ''
  let state: State = 'idle'
  let isSubmitting = false
  let inputEl: HTMLInputElement | null = null
  $: trimmedTitle = title.trim()
  $: canCheck = trimmedTitle.length > 0 && state !== 'checking'
  $: canSubmit = state === 'available' && !isSubmitting

  $: if (show) {
    reset()
    void tick().then(() => {
      inputEl?.focus()
    })
  }

  function reset() {
    title = ''
    state = 'idle'
    isSubmitting = false
  }

  async function check() {
    if (!trimmedTitle) return

    state = 'checking'
    try {
      const exists = await titleExist(trimmedTitle)
      state = exists ? 'exists' : 'available'
    } catch {
      state = 'idle'
    }
  }

  function onInput(event: Event) {
    title = (event.target as HTMLInputElement).value
    if (state !== 'idle' && state !== 'checking') {
      state = 'idle'
    }
  }

  async function ok() {
    if (!canSubmit) return

    isSubmitting = true
    const [, err] = await httpy.post('/api/write-request', {
      title: trimmedTitle,
    })

    if (err) {
      console.error(err)
      showToast('등록에 실패했습니다. 잠시 후 다시 시도해주세요.')
      reset()
      return
    }

    dispatch('close')
    showToast('등록 완료')
    reset()
  }

  function cancel() {
    dispatch('close')
    reset()
  }
</script>

<ZModal {show} okDisabled={!canSubmit} okColor="primary" on:ok={ok} on:cancel={cancel}>
  <div class="w-full">
    <h5 class="mb-3 font-semibold">새 작성 요청 등록하기</h5>
    <div class="flex items-center gap-2">
      <input
        bind:this={inputEl}
        value={title}
        type="text"
        class="flex-1 rounded border p-1 px-2"
        placeholder="제목 입력"
        on:input={onInput}
      />
      <button
        type="button"
        class="relative flex items-center gap-1 rounded border px-3 py-1 text-sm disabled:opacity-40"
        disabled={!canCheck}
        on:click={check}
      >
        중복확인
      </button>
    </div>
    <div class="mt-2 min-h-1.5">
      {#if state === 'checking'}
        <div class="progress-wrap h-1">
          <div class="progress-bar"></div>
        </div>
      {:else if state === 'available'}
        <div class="h-1 w-full rounded bg-green-500"></div>
      {:else if state === 'exists'}
        <div class="h-1 w-full rounded bg-red-500"></div>
      {/if}
    </div>
    {#if state === 'exists'}
      <div class="mt-2 text-sm text-red-500">'{trimmedTitle}' 문서는 이미 있습니다.</div>
    {/if}
  </div>
</ZModal>

<style>
  .progress-wrap {
    width: 100%;
    overflow: hidden;
    background: rgba(5, 114, 206, 0.05);
  }

  .progress-bar {
    height: 100%;
    width: 100%;
    animation: indeterminateAnimation 1s infinite linear;
    transform-origin: 0% 50%;
    background: rgb(5, 114, 206);
  }

  @keyframes indeterminateAnimation {
    0% {
      transform: translateX(0) scaleX(0);
    }

    40% {
      transform: translateX(0) scaleX(0.4);
    }

    100% {
      transform: translateX(100%) scaleX(0.5);
    }
  }
</style>

// vue/src/views/tool/writeRequest/WriteRequestNew.vue
<script setup lang="ts">
import CProgressBar from '@common/components/CProgressBar.vue'
import { showToast } from '@common/ui/toast/toast'
import ZModal from '@common/ui/ZModal.vue'
import httpy from '@common/utils/httpy'
import { computed, nextTick,ref, watch } from 'vue'

import titleExist from '@/utils/mediawiki'

const emit = defineEmits<{
  (e: 'close'): void
}>()

const props = defineProps<{ show: boolean }>()

type State = 'idle' | 'checking' | 'available' | 'exists'

const title = ref('')
const state = ref<State>('idle')
const isSubmitting = ref(false)

const input = ref<HTMLInputElement | null>(null)
const trimmedTitle = computed(() => title.value.trim())

const canCheck = computed(() => trimmedTitle.value.length > 0 && state.value !== 'checking')
const canSubmit = computed(() => state.value === 'available' && !isSubmitting.value)

function reset() {
  title.value = ''
  state.value = 'idle'
  isSubmitting.value = false
}

async function check() {
  if (!trimmedTitle.value) return

  state.value = 'checking'
  try {
    const exists = await titleExist(trimmedTitle.value)
    state.value = exists ? 'exists' : 'available'
  } catch {
    state.value = 'idle'
  }
}

function onInput(e: Event) {
  const val = (e.target as HTMLInputElement).value
  title.value = val
  if (state.value !== 'idle' && state.value !== 'checking') {
    state.value = 'idle'
  }
}

async function ok() {
  if (!canSubmit.value) return

  isSubmitting.value = true
  const [, err] = await httpy.post<unknown>('/api/write-request', {
    title: trimmedTitle.value,
  })
  if (err) {
    console.error(err)
    showToast('등록에 실패했습니다. 잠시 후 다시 시도해주세요.')
    reset()
    return
  }

  emit('close')
  showToast('등록 완료')
  reset()
}

function cancel() {
  emit('close')
  reset()
}

watch(
  () => props.show,
  (show) => {
    if (show) {
      reset()
      nextTick(() => input.value?.focus())
    }
  },
)
</script>

<template>
  <ZModal :show="show" :okDisabled="!canSubmit" okColor="primary" @ok="ok" @cancel="cancel">
    <div class="w-full">
      <h5 class="mb-3 font-semibold">새 작성 요청 등록하기</h5>
      <div class="flex items-center gap-2">
        <input ref="input" :value="title" type="text" class="flex-1 border rounded p-1 px-2" placeholder="제목 입력"
          @input="onInput" />
        <button type="button"
          class="relative px-3 py-1 rounded border text-sm disabled:opacity-40 flex items-center gap-1"
          :disabled="!canCheck" @click="check">
          중복확인
        </button>
      </div>
      <div class="mt-2 min-h-[6px]">
        <CProgressBar v-if="state === 'checking'" :indeterminate="true" class="h-1" />
        <div v-else-if="state === 'available'" class="h-1 w-full bg-green-500 rounded" />
        <div v-else-if="state === 'exists'" class="h-1 w-full bg-red-500 rounded" />
      </div>
      <div v-if="state === 'exists'" class="mt-2 text-sm text-red-500">
        '{{ trimmedTitle }}' 문서는 이미 있습니다.
      </div>
    </div>
  </ZModal>
</template>
