// mwz/skins/ZetaSkin/svelte/src/components/sandbox/SandboxFrame.svelte
<!-- SandboxFrame.svelte -->
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from 'svelte'

  import buildHtml from './buildHtml'
  import ResizableBox from './ResizableBox.svelte'
  import type { SandboxLog } from './types'

  export let id: string
  export let html: string
  export let js: string
  export let resizable = false
  export let className = ''

  const dispatch = createEventDispatcher<{ 'update:logs': SandboxLog[] }>()

  let iframe: HTMLIFrameElement | null = null
  let logs: SandboxLog[] = []

  const handleSandboxLog = (log: SandboxLog) => {
    logs = [...logs, log]
    dispatch('update:logs', logs)
  }

  const run = () => {
    logs = []
    dispatch('update:logs', logs)

    if (!iframe) return
    const content = buildHtml(id, html, js)
    iframe.srcdoc = content
  }

  export function refresh() {
    run()
  }

  onMount(() => {
    ;(window as unknown as Record<string, unknown>)[id] = handleSandboxLog
    run()
  })

  onDestroy(() => {
    const win = window as unknown as Record<string, unknown>
    if (win[id] === handleSandboxLog) {
      delete win[id]
    }
  })
</script>

{#if resizable}
  <ResizableBox className={`h-full rounded ${className}`}>
    <iframe bind:this={iframe} title={`sandbox-${id}`} class="w-full h-full border-0 bg-white"></iframe>
  </ResizableBox>
{:else}
  <div class={`h-full rounded ${className}`}>
    <iframe bind:this={iframe} title={`sandbox-${id}`} class="w-full h-full border-0 bg-white"></iframe>
  </div>
{/if}

// vue/common/components/sandbox/SandboxFrame.vue
<!-- SandboxFrame.vue -->
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'

import buildHtml from './buildHtml'
import ResizableBox from './ResizableBox.vue'
import type { SandboxLog } from './types'

declare global {
  interface Window {
    [key: string]: unknown
  }
}

const props = withDefaults(
  defineProps<{
    id: string
    html: string
    js: string
    resizable?: boolean
  }>(),
  {
    resizable: false,
  },
)

const emit = defineEmits<{
  (e: 'update:logs', logs: SandboxLog[]): void
}>()

const iframe = ref<HTMLIFrameElement | null>(null)
const logs = ref<SandboxLog[]>([])

const handleSandboxLog = (log: SandboxLog) => {
  logs.value.push(log)
  emit('update:logs', logs.value)
}

const run = () => {
  logs.value = []
  emit('update:logs', logs.value)

  if (!iframe.value) return
  const content = buildHtml(props.id, props.html, props.js)
  iframe.value.srcdoc = content
}

defineExpose({ run })

onMounted(() => {
  window[props.id] = handleSandboxLog
  run()
})

onBeforeUnmount(() => {
  if (window[props.id] === handleSandboxLog) {
    delete window[props.id]
  }
})
</script>

<template>
  <component :is="props.resizable ? ResizableBox : 'div'" class="h-full rounded">
    <iframe ref="iframe" class="w-full h-full border-0 bg-white" />
  </component>
</template>
