// svelte/src/routes/forum/components/ForumPostForm.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  import ZButton from '$shared/ui/ZButton.svelte'

  import type { ForumPostFormValue } from './types'

  export let modelValue: ForumPostFormValue
  export let submitText: string
  export let submitting = false
  export let titleError: string | null = null
  export let bodyError: string | null = null

  export let onSubmit: () => void = () => {}
  export let onCancel: () => void = () => {}
  export let onClearTitleError: () => void = () => {}
  export let onClearBodyError: () => void = () => {}

  let EditorApex: (typeof import('../editor/EditorApex.svelte'))['default'] | null = null

  onMount(async () => {
    const mod = await import('../editor/EditorApex.svelte')
    EditorApex = mod.default
  })

  let title = modelValue.title
  let body = modelValue.body

  $: if (modelValue.title !== title) title = modelValue.title
  $: if (modelValue.body !== body) body = modelValue.body

  $: disabled = !title.trim() || !body.trim() || submitting

  function update(patch: Partial<ForumPostFormValue>) {
    modelValue = { ...modelValue, ...patch }
  }
</script>

<div class="space-y-4">
  <div class="flex items-center">
    <select
      value={modelValue.cat}
      on:change={(e) => update({ cat: (e.target as HTMLSelectElement).value })}
      class="my-3 w-auto rounded border bg-white p-1 text-sm text-gray-900 dark:bg-black dark:text-gray-100"
    >
      <option value="질문">질문</option>
      <option value="잡담">잡담</option>
      <option value="인사">인사</option>
      <option value="기타">기타</option>
    </select>
  </div>

  <div>
    <input
      value={title}
      on:input={(e) => {
        onClearTitleError()
        title = (e.target as HTMLInputElement).value
        update({ title })
      }}
      type="text"
      placeholder="제목을 입력해 주세요"
      class={`block w-full rounded border bg-white px-4 py-2 text-gray-900 outline-0 dark:bg-black dark:text-gray-300 ${
        titleError ? 'border-red-300 dark:border-red-700' : ''
      }`}
    />
    {#if titleError}
      <div class="text-sm text-red-400">{titleError}</div>
    {/if}
  </div>

  <div>
    <div class={bodyError ? 'border border-red-300 dark:border-red-700' : ''}>
      {#if EditorApex}
        <svelte:component
          this={EditorApex}
          modelValue={body}
          onModelValueChange={(value: string) => {
            body = value
            onClearBodyError()
            update({ body })
          }}
        />
      {:else}
        <div class="p-4 text-sm text-gray-500">에디터 로딩 중...</div>
      {/if}
    </div>
    {#if bodyError}
      <div class="text-sm text-red-400">{bodyError}</div>
    {/if}
  </div>

  <div class="my-4 flex justify-center gap-3">
    <ZButton color="primary" {disabled} onclick={onSubmit}>
      {submitText}
    </ZButton>
    <ZButton onclick={onCancel}>취소</ZButton>
  </div>
</div>

// vue/src/views/forum/components/ForumPostForm.vue
<!-- ForumPostForm.vue -->
<script setup lang="ts">
import ZButton from '@common/ui/ZButton.vue'
import { computed } from 'vue'

import EditorApex from '../editor/EditorApex.vue'

export interface ForumPostFormValue {
  cat: string
  title: string
  body: string
}

const props = defineProps<{
  modelValue: ForumPostFormValue
  submitText: string
  submitting?: boolean
  titleError?: string | null
  bodyError?: string | null
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', v: ForumPostFormValue): void
  (e: 'submit'): void
  (e: 'cancel'): void
  (e: 'clearTitleError'): void
  (e: 'clearBodyError'): void
}>()

const disabled = computed(() =>
  !props.modelValue.title.trim() || !props.modelValue.body.trim() || props.submitting
)

const update = (patch: Partial<ForumPostFormValue>) => {
  emit('update:modelValue', { ...props.modelValue, ...patch })
}
</script>

<template>
  <div class="space-y-4">
    <div class="flex items-center">
      <select :value="modelValue.cat" @change="update({ cat: ($event.target as HTMLSelectElement).value })"
        class="my-3 border text-sm rounded w-auto p-1 bg-white dark:bg-black text-gray-900 dark:text-gray-100">
        <option value="질문">질문</option>
        <option value="잡담">잡담</option>
        <option value="인사">인사</option>
        <option value="기타">기타</option>
      </select>
    </div>

    <div>
      <input :value="modelValue.title"
        @input="emit('clearTitleError'); update({ title: ($event.target as HTMLInputElement).value })" type="text"
        placeholder="제목을 입력해 주세요"
        class="border rounded block w-full px-4 py-2 outline-0 bg-white dark:bg-black text-gray-900 dark:text-gray-300"
        :class="{ 'border-red-300 dark:border-red-700': !!titleError }" />
      <div v-if="titleError" class="text-sm text-red-400">
        {{ titleError }}
      </div>
    </div>

    <div>
      <div :class="{ 'border border-red-300 dark:border-red-700': !!bodyError }">
        <EditorApex :model-value="modelValue.body"
          @update:model-value="emit('clearBodyError'); update({ body: $event })" />
      </div>
      <div v-if="bodyError" class="text-sm text-red-400">
        {{ bodyError }}
      </div>
    </div>

    <div class="my-4 flex justify-center gap-3">
      <ZButton color="primary" :disabled="disabled" @click="emit('submit')">
        {{ submitText }}
      </ZButton>
      <ZButton @click="emit('cancel')">
        취소
      </ZButton>
    </div>
  </div>
</template>
