// svelte/src/shared/components/navbar/CSearch.svelte
<svelte:options customElement={{ tag: 'c-search', shadow: 'none' }} />

<script lang="ts">
  import { mdiHistory, mdiMagnify, mdiShuffle } from '@mdi/js'
  import { onDestroy } from 'svelte'

  import { useDismissable } from '$shared/composables/useDismissable'
  import ZIcon from '$shared/ui/ZIcon.svelte'
  import getShortcut from '$shared/utils/shortcut'

  interface Page {
    description: string
    excerpt: string
    id: number
    key: string
    matched_title: string
    thumbnail: Record<string, unknown>
    title: string
  }
  interface SearchResponse {
    pages?: Page[]
    [k: string]: unknown
  }

  let root: HTMLElement | null = null
  let expanded = false
  let keyword = ''
  let pages: Page[] = []

  let kIndex = -1
  let hIndex = -1

  let aborter: AbortController | null = null
  let debounceId: ReturnType<typeof setTimeout> | null = null

  const searchTitle = `검색 (${getShortcut('f')})`
  const randomTitle = `랜덤 (${getShortcut('x')})`
  const recentTitle = `바뀐글 (${getShortcut('r')})`

  $: displayQuery = kIndex >= 0 && kIndex < pages.length ? (pages[kIndex]?.title ?? keyword) : keyword

  $: currentIndex = hIndex >= 0 ? hIndex : kIndex

  function close() {
    expanded = false
    kIndex = -1
    hIndex = -1
  }

  useDismissable(() => root, {
    enabled: () => expanded,
    onDismiss: close,
  })

  async function fetchData(q: string) {
    const trimmed = q.trim()
    if (!trimmed) return

    aborter?.abort()
    const controller = new AbortController()
    aborter = controller

    try {
      const url = `/w/rest.php/v1/search/title?${new URLSearchParams({ q: trimmed, limit: '10' })}`
      const res = await fetch(url, { signal: controller.signal })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const json = (await res.json()) as SearchResponse
      pages = Array.isArray(json.pages) ? json.pages : []
      expanded = true
      kIndex = -1
      hIndex = -1
    } catch (e: unknown) {
      if (e instanceof DOMException && e.name === 'AbortError') return
      console.error('[search]', e)
    } finally {
      if (aborter === controller) aborter = null
    }
  }

  function debouncedFetch(q: string) {
    if (debounceId) clearTimeout(debounceId)
    debounceId = setTimeout(() => fetchData(q), 400)
  }

  function onInput(e: Event) {
    const val = (e.target as HTMLInputElement).value
    keyword = val
    kIndex = -1
    hIndex = -1

    if (!val.trim()) {
      aborter?.abort()
      pages = []
      expanded = false
      return
    }
    debouncedFetch(val)
  }

  function onFocus() {
    if (keyword.trim()) expanded = true
  }

  function handleUpDown(offset: number) {
    const max = pages.length
    let next = kIndex + offset
    if (next < -1) next = max
    if (next > max) next = -1
    kIndex = next
  }

  function goToSearch() {
    if (typeof window === 'undefined') return

    const base = new URL('/w/index.php', window.location.origin)
    base.searchParams.set('title', '특수:검색')

    if (kIndex < 0) {
      base.searchParams.set('search', displayQuery)
    } else if (kIndex === pages.length) {
      base.searchParams.set('search', displayQuery)
      base.searchParams.set('fulltext', '1')
      base.searchParams.set('ns0', '1')
    } else {
      base.searchParams.set('search', pages[kIndex]?.title ?? displayQuery)
    }

    close()
    window.location.href = base.toString()
  }

  function onClick() {
    kIndex = -1
    goToSearch()
  }

  function onKeyDown(e: KeyboardEvent) {
    if (e.key === 'ArrowUp') {
      e.preventDefault()
      handleUpDown(-1)
    } else if (e.key === 'ArrowDown') {
      e.preventDefault()
      handleUpDown(1)
    } else if (e.key === 'Enter') {
      goToSearch()
    } else if (e.key === 'Escape') {
      e.preventDefault()
      close()
    }
  }

  function escapeHTML(s: string) {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;')
  }

  function highlight(needle: string, haystack: string) {
    const safeNeedle = needle.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    if (!safeNeedle) return escapeHTML(haystack)
    const re = new RegExp(safeNeedle, 'giu')
    return escapeHTML(haystack).replace(re, (s) => `<b>${escapeHTML(s)}</b>`)
  }

  onDestroy(() => {
    aborter?.abort()
  })
</script>

<div class="z-text ml-auto flex w-full md:max-w-2xl">
  <div class="m-1.5 grow">
    <div bind:this={root} class="relative" role="search">
      <div class={`flex h-9 z-base rounded-t ${!expanded || !keyword.trim().length ? 'rounded-b' : ''}`}>
        <!-- svelte-ignore a11y_accesskey -->
        <input
          accesskey="f"
          aria-label="search"
          type="search"
          class="grow h-full bg-transparent px-3 outline-0"
          name="search"
          placeholder="검색..."
          title={searchTitle}
          autocomplete="off"
          value={displayQuery}
          on:input={onInput}
          on:focus={onFocus}
          on:keydown={onKeyDown}
        />
        <button type="button" class="z-10 h-full w-12 flex-none bg-transparent focus:text-blue-700" on:click={onClick}>
          <ZIcon path={mdiMagnify} size={24} />
        </button>
      </div>

      <div class={`absolute z-40 w-full z-base border rounded-b ${!expanded || !keyword.trim().length ? 'hidden' : ''}`}>
        <nav aria-label="검색 제안" on:mouseleave={() => (hIndex = -1)}>
          {#if pages.length}
            {#each pages as p, i (p.id)}
              <div>
                <a
                  class={`block p-1.5 px-3 z-text ${currentIndex === i ? 'focused' : ''}`}
                  href={`/w/index.php?title=특수:검색&search=${encodeURIComponent(p.title)}`}
                  rel="external"
                  data-sveltekit-reload
                  on:mouseenter={() => (hIndex = i)}
                  on:focus={() => (hIndex = i)}
                >
                  <!-- eslint-disable-next-line svelte/no-at-html-tags -->
                  <span>{@html highlight(keyword, p.title)}</span>
                </a>
              </div>
            {/each}
          {/if}

          <a
            class={`block p-2 px-3 border-t rounded-b z-text ${currentIndex === pages.length ? 'focused' : ''}`}
            href={`/w/index.php?title=특수:검색&fulltext=1&search=${encodeURIComponent(keyword)}`}
            rel="external"
            data-sveltekit-reload
            on:mouseenter={() => (hIndex = pages.length)}
            on:focus={() => (hIndex = pages.length)}
          >
            <ZIcon path={mdiMagnify} />
            <b>{keyword}</b> 항목이 포함된 글 검색
          </a>
        </nav>
      </div>
    </div>
  </div>

  <div class="flex flex-none">
    <!-- svelte-ignore a11y_accesskey -->
    <a href="/wiki/특수:임의문서" rel="external" class="navlink" title={randomTitle} accesskey="x" data-sveltekit-reload>
      <ZIcon path={mdiShuffle} class="h-5 w-5" />
      <span class="ml-1 hidden xl:inline">랜덤</span>
    </a>
    <!-- svelte-ignore a11y_accesskey -->
    <a href="/wiki/특수:최근바뀜" rel="external" class="navlink" title={recentTitle} accesskey="r" data-sveltekit-reload>
      <ZIcon path={mdiHistory} class="h-5 w-5" />
      <span class="ml-1 hidden xl:inline">바뀐글</span>
    </a>
  </div>
</div>

<style>
  .focused {
    background-color: rgb(79 70 229 / 0.7);
    color: white;
    text-decoration: none;
  }
</style>

// vue/common/components/navbar/CSearch.vue
<!-- CNavbarSearch.vue -->
<script setup lang="ts">
import { useDismissable } from '@common/composables/useDismissable'
import ZIcon from '@common/ui/ZIcon.vue'
import { mdiHistory, mdiMagnify, mdiShuffle } from '@mdi/js'
import { useDebounceFn } from '@vueuse/core'
import { computed, onBeforeUnmount, ref } from 'vue'

interface Page {
  description: string
  excerpt: string
  id: number
  key: string
  matched_title: string
  thumbnail: Record<string, unknown>
  title: string
}
interface SearchResponse { pages?: Page[];[k: string]: unknown }

const root = ref<HTMLElement | null>(null)
const expanded = ref(false)
const keyword = ref('')
const pages = ref<Page[]>([])

const kIndex = ref(-1)
const hIndex = ref(-1)

const aborter = ref<AbortController | null>(null)

const displayQuery = computed(() =>
  kIndex.value >= 0 && kIndex.value < pages.value.length
    ? pages.value[kIndex.value].title
    : keyword.value
)

const currentIndex = computed(() => (hIndex.value >= 0 ? hIndex.value : kIndex.value))

function close() {
  expanded.value = false
  kIndex.value = -1
  hIndex.value = -1
}

useDismissable(root, {
  enabled: expanded,
  onDismiss: close,
})

async function fetchData(q: string) {
  const trimmed = q.trim()
  if (!trimmed) return

  aborter.value?.abort()
  const controller = new AbortController()
  aborter.value = controller

  try {
    const url = `/w/rest.php/v1/search/title?${new URLSearchParams({ q: trimmed, limit: '10' })}`
    const res = await fetch(url, { signal: controller.signal })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const json = (await res.json()) as SearchResponse
    pages.value = Array.isArray(json.pages) ? json.pages : []
    expanded.value = true
    kIndex.value = -1
    hIndex.value = -1
  } catch (e: unknown) {
    if (e instanceof DOMException && e.name === 'AbortError') return
    console.error('[search]', e)
  } finally {
    if (aborter.value === controller) aborter.value = null
  }
}

const debouncedFetch = useDebounceFn((q: string) => fetchData(q), 400)

function onInput(e: Event) {
  const val = (e.target as HTMLInputElement).value
  keyword.value = val
  kIndex.value = -1
  hIndex.value = -1

  if (!val.trim()) {
    aborter.value?.abort()
    pages.value = []
    expanded.value = false
    return
  }
  debouncedFetch(val)
}

function onFocus() {
  if (keyword.value.trim()) expanded.value = true
}

function handleUpDown(offset: number) {
  const max = pages.value.length
  let next = kIndex.value + offset
  if (next < -1) next = max
  if (next > max) next = -1
  kIndex.value = next
}

function goToSearch() {
  const base = new URL('/w/index.php', window.location.origin)
  base.searchParams.set('title', '특수:검색')

  if (kIndex.value < 0) {
    base.searchParams.set('search', displayQuery.value)
  } else if (kIndex.value === pages.value.length) {
    base.searchParams.set('search', displayQuery.value)
    base.searchParams.set('fulltext', '1')
    base.searchParams.set('ns0', '1')
  } else {
    base.searchParams.set('search', pages.value[kIndex.value].title)
  }

  close()
  window.location.href = base.toString()
}

const onKeyUp = () => handleUpDown(-1)
const onKeyDown = () => handleUpDown(1)
const onKeyEnter = () => goToSearch()
const onKeyEscape = () => close()

const onClick = () => { kIndex.value = -1; goToSearch() }

function escapeHTML(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}
function highlight(needle: string, haystack: string) {
  const safeNeedle = needle.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  if (!safeNeedle) return escapeHTML(haystack)
  const re = new RegExp(safeNeedle, 'giu')
  return escapeHTML(haystack).replace(re, s => `<b>${escapeHTML(s)}</b>`)
}

onBeforeUnmount(() => { aborter.value?.abort() })
</script>

<template>
  <div class="flex ml-auto md:max-w-2xl w-full z-text">
    <div class="grow m-1.5">
      <div ref="root" class="relative" @keydown.up.prevent="onKeyUp" @keydown.down.prevent="onKeyDown"
        @keydown.enter="onKeyEnter" @keydown.escape.prevent="onKeyEscape">
        <div class="flex h-9 z-bg rounded-t" :class="{ 'rounded-b': !expanded || !keyword.trim().length }">
          <input aria-label="search" type="search" class="grow px-3 h-full outline-0 bg-transparent" name="search"
            placeholder="검색..." title="검색 [alt-shift-f]" accesskey="f" autocomplete="off" :value="displayQuery"
            @input="onInput" @focus="onFocus" />
          <button type="button" class="flex-none w-12 h-full z-10 bg-transparent focus:text-blue-700" @click="onClick">
            <ZIcon :path="mdiMagnify" :size="24" />
          </button>
        </div>

        <div class="absolute z-40 w-full z-bg border rounded-b" :class="{ hidden: !expanded || !keyword.trim().length }"
          @mouseleave="hIndex = -1">
          <div v-if="pages.length">
            <div v-for="(p, i) in pages" :key="p.id">
              <a class="block p-1.5 px-3 z-text" :class="{ focused: currentIndex === i }"
                :href="`/w/index.php?title=특수:검색&search=${encodeURIComponent(p.title)}`" @mouseenter="hIndex = i"
                @focus="hIndex = i">
                <span v-html="highlight(keyword, p.title)" />
              </a>
            </div>
          </div>

          <a class="block p-2 px-3 border-t rounded-b z-text"
            :href="`/w/index.php?title=특수:검색&fulltext=1&search=${encodeURIComponent(keyword)}`"
            :class="{ focused: currentIndex === pages.length }" @mouseenter="hIndex = pages.length"
            @focus="hIndex = pages.length">
            <ZIcon :path="mdiMagnify" />
            <b>{{ keyword }}</b> 항목이 포함된 글 검색
          </a>
        </div>
      </div>
    </div>

    <div class="flex-none flex">
      <a href="/wiki/특수:임의문서" class="navlink" title="랜덤">
        <ZIcon :path="mdiShuffle" class="w-5 h-5" />
        <span class="hidden xl:inline ml-1">랜덤</span>
      </a>
      <a href="/wiki/특수:최근바뀜" class="navlink" title="바뀐글">
        <ZIcon :path="mdiHistory" class="w-5 h-5" />
        <span class="hidden xl:inline ml-1">바뀐글</span>
      </a>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.focused {
  @apply bg-indigo-600/70 text-white no-underline;
}
</style>
