// mwz/skins/ZetaSkin/vue/src/components/PageMeta.vue
<!-- PageMeta.vue -->
<script setup lang="ts">
import AvatarIcon from '@common/components/avatar/AvatarIcon.vue'
import ZIcon from '@common/ui/ZIcon.vue'
import { mdiClockOutline } from '@mdi/js';

import getRLCONF from '@/utils/rlconf'

defineProps({
  historyhref: { type: String, required: true },
})

const { lastmod, contributors } = getRLCONF()
</script>

<template>
  <template v-if="contributors.length">
    <a :href="historyhref" class="z-text2">
      <ZIcon :path="mdiClockOutline" />
      {{ `${lastmod.substring(0, 4)}-${lastmod.substring(4, 6)}-${lastmod.substring(6, 8)}` }}
    </a>
    <span class="pl-3 -space-x-0.5">
      <a v-for="u in contributors" :key="u.id" :href="`/profile/${u.name}`">
        <AvatarIcon :user="u" :showBorder="true" />
      </a>
    </span>
  </template>
</template>

// mwz/skins/ZetaSkin/svelte/src/components/PageMeta.svelte
<svelte:options customElement={{ tag: 'page-meta', shadow: 'none' }} />

<script lang="ts">
  import { mdiClockOutline } from '@mdi/js'

  import getRLCONF from '$lib/utils/rlconf'
  import AvatarIcon from '$shared/components/avatar/AvatarIcon.svelte'
  import ZIcon from '$shared/ui/ZIcon.svelte'

  export let historyhref: string

  const { lastmod, contributors } = getRLCONF()

  const asDate = (v: string) => (v && v.length >= 8 ? `${v.substring(0, 4)}-${v.substring(4, 6)}-${v.substring(6, 8)}` : v)
</script>

{#if contributors?.length}
  <a href={historyhref} class="z-text2 inline-flex items-center gap-1">
    <ZIcon path={mdiClockOutline} class="h-4 w-4" />
    {asDate(lastmod)}
  </a>
  <span class="pl-3 -space-x-0.5">
    {#each contributors as u (u.id)}
      <a href={`/profile/${u.name}`}>
        <AvatarIcon user={u} showBorder={true} />
      </a>
    {/each}
  </span>
{/if}
