// svelte/src/shared/components/CSiteRemocon.svelte
<svelte:options customElement={{ tag: 'c-site-remocon', shadow: 'none' }} />

<script lang="ts">
  import { mdiChevronDown, mdiChevronUp, mdiWeatherNight } from '@mdi/js'
  import { onMount } from 'svelte'

  import ZIcon from '$shared/ui/ZIcon.svelte'
  import { scrollToBottom, scrollToTop } from '$shared/utils/scroll'

  let isDark = false

  const toggleDark = () => {
    isDark = !isDark
    document.documentElement.classList.toggle('dark', isDark)
    localStorage.setItem('theme', isDark ? 'dark' : 'light')
  }

  onMount(() => {
    const stored = localStorage.getItem('theme')
    if (stored === 'dark') {
      isDark = true
      document.documentElement.classList.add('dark')
      return
    }
    if (stored === 'light') {
      isDark = false
      document.documentElement.classList.remove('dark')
      return
    }

    if (window.matchMedia?.('(prefers-color-scheme: dark)').matches) {
      isDark = true
      document.documentElement.classList.add('dark')
    }
  })
</script>

<div class="fixed bottom-0 right-0 z-40 print:hidden">
  <div class="z-50 flex gap-1 text-white opacity-80">
    <button type="button" class="cursor-pointer rounded bg-[#8888] p-1.5 dark:text-yellow-500" on:click={toggleDark}>
      <ZIcon path={mdiWeatherNight} size={24} />
    </button>
    <button type="button" class="cursor-pointer rounded bg-[#8888] p-1.5" on:click={scrollToTop}>
      <ZIcon path={mdiChevronUp} size={24} />
    </button>
    <button type="button" class="cursor-pointer rounded bg-[#8888] p-1.5" on:click={scrollToBottom}>
      <ZIcon path={mdiChevronDown} size={24} />
    </button>
  </div>
</div>

// vue/common/components/CSiteRemocon.vue
<script setup lang="ts">
import { mdiChevronDown, mdiChevronUp, mdiWeatherNight } from '@mdi/js'
import { useDark, useToggle } from '@vueuse/core'

import ZIcon from '@common/ui/ZIcon.vue'
import { scrollToTop, scrollToBottom } from '@common/utils/scroll'

const isDark = useDark()
const toggleDark = useToggle(isDark)
</script>

<template>
  <div class="fixed bottom-0 right-0 z-40 print:hidden">
    <div class="z-50 mx-0.5 text-white opacity-80">
      <button type="button" @click="toggleDark()">
        <ZIcon :class="{ 'text-yellow-500': isDark }" :path="mdiWeatherNight" />
      </button>
      <button type="button" @click="scrollToTop">
        <ZIcon :path="mdiChevronUp" />
      </button>
      <button type="button" @click="scrollToBottom">
        <ZIcon :path="mdiChevronDown" />
      </button>
    </div>
  </div>
</template>

<style scoped>
button {
  @apply p-1.5 ml-0.5 rounded bg-[#8888];
}

svg {
  @apply w-6 h-6;
}
</style>
