// mwz/skins/ZetaSkin/vue/src/components/runbox/BoxFront.vue
<script setup lang="ts">
import { SandboxConsole, SandboxFrame, type SandboxLog } from '@common/components/sandbox'
import { computed, nextTick,ref, watch } from 'vue'

import type { Job } from './types'

const props = defineProps<{
  job: Job
  seq: number
}>()

const { job, seq } = props

const getCode = (lang: string) => job.boxes
  .filter((b) => b.lang === lang)
  .map((b) => b.text)
  .join('\n')
  .trim()

const htmlCode = computed(() => getCode('html'))
const jsCode = computed(() => getCode('javascript'))

const sandboxId = `sandbox-${job.id}-${seq}`

const logs = ref<SandboxLog[]>([])
const updateLogs = (newLogs: SandboxLog[]) => {
  logs.value = newLogs
}

const sandboxRef = ref<InstanceType<typeof SandboxFrame> | null>(null)
const consoleRef = ref<HTMLElement | null>(null)

watch(
  () => logs.value.length,
  async () => {
    await nextTick()
    const el = consoleRef.value
    if (!el) return
    el.scrollTop = el.scrollHeight
  }
)
</script>

<template>
  <slot />
  <div v-if="job.main === seq">
    <SandboxFrame ref="sandboxRef" v-show="htmlCode.length > 0" :id="sandboxId" :html="htmlCode" :js="jsCode"
      :resizable="job.outResize" class="mt-1 h-32 rounded"
      :class="{ hidden: !job.boxes.some((b) => b.lang === 'html') }" @update:logs="updateLogs" />
    <div v-if="logs.length > 0" class="max-h-40 overflow-y-auto mt-1 bg-[var(--console-bg)]" ref="consoleRef">
      <SandboxConsole :logs="logs" class="rounded-lg" />
    </div>
  </div>
</template>

// mwz/skins/ZetaSkin/svelte/src/components/runbox/BoxFront.svelte
<script lang="ts">
  import { afterUpdate } from 'svelte'
  import type { Writable } from 'svelte/store'

  import SandboxConsole from '../sandbox/SandboxConsole.svelte'
  import SandboxFrame from '../sandbox/SandboxFrame.svelte'
  import type { SandboxLog } from '../sandbox/types'
  import type { Job } from './types'

  export let job: Writable<Job>
  export let seq: number

  const getCode = (current: Job, lang: string) =>
    current.boxes
      .filter((b) => b.lang === lang)
      .map((b) => b.text)
      .join('\n')
      .trim()

  $: jobValue = $job
  $: htmlCode = getCode(jobValue, 'html')
  $: jsCode = getCode(jobValue, 'javascript')

  $: sandboxId = `sandbox-${jobValue.id}-${seq}`

  let logs: SandboxLog[] = []
  const updateLogs = (e: CustomEvent<SandboxLog[]>) => {
    logs = e.detail
  }

  let consoleRef: HTMLElement | null = null
  let lastLogCount = 0

  afterUpdate(() => {
    if (!consoleRef) return
    if (logs.length === lastLogCount) return
    lastLogCount = logs.length
    consoleRef.scrollTop = consoleRef.scrollHeight
  })
</script>

<slot />

{#if jobValue.main === seq}
  <SandboxFrame
    id={sandboxId}
    html={htmlCode}
    js={jsCode}
    resizable={jobValue.outResize}
    className={`mt-1 h-32 rounded ${!jobValue.boxes.some((b) => b.lang === 'html') ? 'hidden' : ''}`}
    on:update:logs={updateLogs}
  />

  {#if logs.length > 0}
    <div bind:this={consoleRef} class="max-h-40 overflow-y-auto mt-1 bg-[var(--console-bg)]">
      <SandboxConsole {logs} className="rounded-lg" />
    </div>
  {/if}
{/if}
