// mwz/skins/ZetaSkin/vue/src/components/runbox/BoxNotebook.vue
<!-- BoxNotebook.vue -->
<script setup lang="ts">
import { computed } from 'vue'

import NBOutput from './notebook/NBOutput.vue'
import type { Job } from './types'

const props = defineProps<{
  job: Job
  seq: number
}>()

const { job, seq } = props

const nbouts = computed(() => job.notebookOuts[seq] ?? [])
const loaded = computed(() => job.phase != null)
</script>

<template>
  <slot />

  <div v-if="loaded && job.phase === 'succeeded' && nbouts.length">
    <NBOutput v-for="(nbout, i) in nbouts" :key="i" :out="nbout" />
  </div>
</template>

// mwz/skins/ZetaSkin/svelte/src/components/runbox/BoxNotebook.svelte
<!-- BoxNotebook.svelte -->
<script lang="ts">
  import type { Writable } from 'svelte/store'

  import NBOutput from './notebook/NBOutput.svelte'
  import type { Job } from './types'

  export let job: Writable<Job>
  export let seq: number

  $: jobValue = $job
  $: nbouts = jobValue.notebookOuts[seq] ?? []
  $: loaded = jobValue.phase != null
</script>

<slot />

{#if loaded && jobValue.phase === 'succeeded' && nbouts.length}
  {#each nbouts as nbout, i (i)}
    <NBOutput out={nbout} />
  {/each}
{/if}
